# Site settings
title: Test Laure
email: zazoun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test Laure
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zazoun.github.io/" # the base hostname & protocol for your site
twitter_username: Zazoun
github_username:  zazoun
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

# Build settings
markdown: kramdown
gem "github-pages", group: :jekyll_plugins