# Site settings
title: Test Laure
email: zazoun@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test Laure
baseurl: "/zazoun.github.io/" # the subpath of your site, e.g. /blog/
url: "https://zazoun.github.io/" # the base hostname & protocol for your site
twitter_username: Zazoun
github_username:  zazoun

# Build settings
markdown: kramdown
